// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_MAIN  1001
#define IDR_ICO_MAIN  8001



#define IDCB_DIGITS  4003



#define IDCB_STEP  4013

#define ID_CUSTEPC  4015
#define ID_GHEX  4011

#define ID_GENERATE  1

#define IDC_CE  4016
#define IDE_KA  4001
#define IDE_RESULT  4002
#define IDE_T  4004
#define IDE_KH  4006
#define IDE_EPOCH  4009
